name: api

services:
  api:
    image: 'mcr.microsoft.com/devcontainers/javascript-node:20-bullseye'
    command: tail -f /dev/null
    networks:
      - qfy-dev
    ports:
      - 3001:3001
    volumes:
      - ../..:/workspaces:cached

  mysql:
    image: 'mysql:8.4'
    environment:
      MYSQL_ROOT_PASSWORD: dh1NVaJQuhpks1tc74GYdHwei6qaWY5m
      MYSQL_DATABASE: lc_dev
      MYSQL_USER: johndoe
      MYSQL_PASSWORD: vdfmn7pw2u
    networks:
      - qfy-dev
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - qfy-api-mysql-data-dev:/var/lib/mysql

  redis:
    image: 'redis:alpine'
    networks:
      - qfy-dev
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - qfy-api-redis-data-dev:/data

volumes:
  qfy-api-mysql-data-dev:
  qfy-api-redis-data-dev:

networks:
  # The presence of these objects is sufficient to define them
  qfy-dev:
    name: qfy-dev
