name: api

services:
  api:
    image: 'mcr.microsoft.com/devcontainers/javascript-node:20-bullseye'
    command: tail -f /dev/null
    networks:
      - api
    ports:
      - '3000:3000'
    volumes:
      - ../..:/workspaces:cached
  mysql:
    image: 'mysql:8.4'
    environment:
      MYSQL_ROOT_PASSWORD: dh1NVaJQuhpks1tc74GYdHwei6qaWY5m
      MYSQL_DATABASE: legal-consultation-dev
      MYSQL_USER: johndoe
      MYSQL_PASSWORD: 2Dp1pFT9ehMaoefpPLq9VuXqJg7Fc8g8
    networks:
      - api
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: 'redis:alpine'
    networks:
      - api
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:

networks:
  # The presence of these objects is sufficient to define them
  api:
    name: api
